### ISSUE TITLE
QUIC4SAT : focus on the backhaul on hybridation and in sequence

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/QUIC_HIGH_BDP#43]

**Comment by gorryfair** [comment]
I had in mind something an addition section starting something like:

Satellite systems has long been used to support point-to-point links and specialised networks. The predominate current use is as a link-layer for Internet Protocols. Typical example applications include: use as an access technology for remote locations, backup and rapid deployment of new services, transit networks, and backhaul of various types of IP networks, and provision to mobile (maritime, aircraft, etc). The satellite IP network segment usually only forms one part of the end-to-end path. This means user traffic can experince a path that includes satellites satellite capacity together with a wide variety of other network technologies (Ethernet, cable modems, WiFi, cellular, radio links, etc). Although a user can sometimes the presence of the satellite service, a typical user does not deploy special software or applications because they expect a satellite network is being used. Often a user is unaware of the technologies underpinning the links forming the network path.

**Comment by NicoKos** [comment]
Closeb by PR #50
