### ISSUE TITLE
add a section describing new QUIC transport parameter registration 

### ISSUE THREAD

**Issue by emile22** [NicoKos/QUIC_HIGH_BDP#66]

**Comment by NicoKos** [comment]
also, we may want to limit the parameters that would be registered (maxCWND and sRTT e.g.)

**Comment by gorryfair** [comment]
I think you're correct - we need to think of a list of "needed and appropriate parameters is helpful. Hopefully the updated text on QUIC migration clarifies that parameters are not to be shared BETWEEN flows that actually use different paths!
maxCWND - not sure that helps ... because it can be x2 the capacity. Is ssthresth helpful? (or max cwnd without loss... how doe know BDP?)
Min_RTT could be helpful? (at least to confirm you have a satellite path).

It's also important we set time limits for these - because we can create harm as well as good if we persist in using a value for too longer. Even just re-using the busy-hour value in an off-peak time will significantly prejudice performance.
