### ISSUE TITLE
add a comment on ACK clocking

### ISSUE THREAD

**Issue by NicoKos** [NicoKos/QUIC_HIGH_BDP#76]
this solution avoids that bursts of data.
SATCOM systems typically introduce peak-data rate maximum values.

**Comment by gorryfair** [comment]
Is it really the peak data rate maximum value that disrupts the timing of the flow?
I rather suspect more timing disruption occurs from channel access - both in assigning packets (or parts of packets) to time slots, and in allocating time slots via contention or capacity requests.

**Comment by NicoKos** [comment]
I was reading RFC3135 and this point came to my mind. 

"For example, in an
   environment where ACKs may bunch together causing undesirable data
   segment bursts, a TCP PEP may be used to simply modify the ACK
   spacing in order to improve performance."

I thought that reducing bursts may be relevant when there are peak-data rate maximum values but I am proably wrong. 
That is surely something we could discuss during the workshop and in the draft.

**Comment by gorryfair** [comment]
In danger of restating the obvious ;-) ... Excessive bursts are problematic... because they impact RTT accuracy, jitter other flows, and cause premature loss (because the tail of the burst can be clipped by a drop-tail buffer). That said, we should be careful, adaptive fine-grain pacing is also seriously dangerous ... because when you share with a fine-grain paced flow it can persistently consume bottleneck buffers. A fine-grain paced flow can slowly increase until it starves all other flows.

So do we mean sender-bursts (due to ACK-policy, IW, flow-control); or bursts created by satellite equipment (due to scheduling transmission bursts, RRM, etc)?
